### ISSUE TITLE
Add "Renew" functionality

### ISSUE THREAD

**Issue by phg49389** [betheluniversity/classifieds#6]
We were talking about classifieds this morning in Slack, and found that some users were marking old posts as complete and then re-submitting them to make sure that they're on the top of the list. To help save on DB space, we'd like to keep each post only submitted once in theory. As such, we'd like to implement the ability to "renew" a post, and change its posted-on-date value to become when the "renew" button is clicked. However, to avoid spamming this ability, we thought that a post would have to be a certain number of days old before they renew it. Perhaps 3 days? Maybe 7?

**Comment by phg49389** [comment]
During the refactor that I'm doing right now, I discovered that this is already implemented. However, right now it's only available to the user once their post expires. All we'd have to do is change the template to allow them to renew it according to whatever criteria we decide according to my comment above.

**Comment by c-schwarze** [comment]
I don't think we want to explicitly add a button for people to put their post at the top of the list. As we have a way to renew once it is expired, we can close this.

Feel free to open if you disagree.
